### ISSUE TITLE
Problem to change the baud rate of the ESP8266

### ISSUE THREAD

**Issue by dcoredump** [TomerCo/ESP8266-Modules#1]
Hi!

Thanks for your NTP firmware! I am new to ESP8266 but I got it running. But I have some trouble with the used baud rate of 115200 bps. I tried to change the baud rate with AT+CPIOBAUD=19200 which gets an ERROR. With actual "Electrodragon" firmware the command seems to work. Maybe this is  a problem due to 0.9.4-based NTP-firmware?

Is there a change that you build a newer version or do you have an idea how to set the ESP up to use a lower baud rate?

Thanks, Holger

**Comment by TomerCo** [comment]
Hi,

The AT+CPIOBAUD command was changed to AT+IPR.
So just execute AT+IPR=19200 and you should  be good to go.
